---
    - name: Disable ip forwarding
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: '{{ item.value }}'
        sysctl_set: yes
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/90-ip.conf
      loop:
      - name: net.ipv4.ip_forward
        value: 0
      - name: net.ipv6.conf.all.forwarding
        value: 0

    - name: Disable ICMP echo and redirects
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: '{{ item.value }}'
        sysctl_set: yes
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/90-icmp.conf
      loop:
        - name: net.ipv4.icmp_echo_ignore_broadcasts
          value: 1
        - name: net.ipv4.icmp_echo_ignore_all
          value: 1
        - name: net.ipv4.conf.default.accept_redirects
          value: 0
        - name: net.ipv4.conf.all.accept_redirects
          value: 0
        - name: net.ipv6.conf.all.accept_redirects
          value: 0
        - name: net.ipv6.conf.default.accept_redirects
          value: 0
        - name: net.ipv4.conf.default.send_redirects
          value: 0
        - name: net.ipv4.conf.all.send_redirects
          value: 0
